### ISSUE TITLE
Using PremiumDataExchange

### ISSUE THREAD

**Issue by eurekar** [dshipman/pyms#2]
Update: I now understand that the 'name' is arbitrary. The related issue is solved. 

---

Hi, Thank you for creating pyms. As I am learning it with PremiumData, I wonder what the 'name' argument does when creating a PremiumDataExchange object. An example would help. Thanks.

**Comment by dshipman** [comment]
Glad you cleared this up.  Closing issue now as I'm tidying up my github...
